version: 1.0.{build}
environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  
artifacts:
- path: node_modules
  type: WebDeployPackage
deploy:
- provider: Environment
  name: 155
...
