version: 1.0.{build}
build_cloud: Docker
image: Linux
build_script:
- sh: apt-get update 
- sh: curl -sL https://deb.nodesource.com/setup_12.x | bash - &&  apt-get install -y nodejs p7zip-full
- sh: npm install
- sh: 7z a test.7z ./
artifacts:
- path: test.7z
deploy:
- provider: Environment
  name: 155
